project:
  type: website

website:
  title: "Andres Chirinos"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - sobre/index.qmd
      - href: https://andres-chirinos.github.io/notes/
        text: El cuaderno de notas
      - charlas/index.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/andres-chirinos
      - icon: github
        href: https://github.com/andres-chirinos

format:
  html:
    theme: cosmo
    css: libs/styles.css
    toc: true
